name: Packer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [10, 12, 14]
        packerfile:
          - app.json
          - db.json
          - immutable.json
          - ubuntu16.json
    steps:
      - uses: actions/checkout@v2
      - name: Использование Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: packer validate -var-file=packer/variables.json.example packer/${{ matrix.packerfile }}



